[package]
name = "lucem"
version = "3.0.0"
license = "GPL3"
kind = "Binary"
backend = "C"
binaries = ["lucem"]

[toolchain]
version = "2.2.0"

[dependencies]
jsony = ">= 1.1.5"
url = ">= 0.0.0"
shakar = ">= 0.1.3"
results = ">= 0.5.1"
owlkettle = ">= 3.0.0"
curly = ">= 1.1.1"
pretty = ">= 0.2.0"
chronicles = ">= 0.12.2"
